---
title: Your awesome title
timezone: UTC
collections:
  iamf-details:
    title: IAMF Details
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: team
  values:
    designation: ''
    image: ''
    profile_url: ''
email: your-email@domain.com
description: "\n"
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
