---
title: I AM FOUNDATION
timezone: America/New_York
collections:
  advisory-board:
    title: Advisory Board
    output: true
  board-of-overseers:
    title: Board of Overseers
    output: true
  events:
    title: Events
    output: true
  iamf-details:
    title: Footer
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default_page
    weight: '10'
    menu_element: main
- scope:
    path: ''
    type: team
  values:
    designation: ''
    image: ''
    profile_url: ''
- scope:
    path: ''
    type: advisory-board
  values:
    designation: ''
    company: ''
    location: ''
- scope:
    path: ''
    type: board-of-overseers
  values:
    designation: ''
    company: ''
    location: ''
- scope:
    path: ''
    type: events
  values:
    title: ''
    image: ''
    event_date: ''
    venue: ''
    external_url: ''
email: hello@iamfoundation.org
description: "\n"
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
