---
title: Your awesome title
timezone: UTC
collections:
  advisory-board:
    title: Advisory Board
    output: true
  board-of-overseers:
    title: Board of Overseers
    output: true
  event:
    title: Event
    output: true
  iamf-details:
    title: IAMF Details
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: team
  values:
    designation: ''
    image: ''
    profile_url: ''
- scope:
    path: ''
    type: advisory-board
  values:
    designation: ''
    company: ''
    location: ''
- scope:
    path: ''
    type: board-of-overseers
  values:
    designation: ''
    company: ''
    location: ''
- scope:
    path: ''
    type: event
  values:
    title: ''
    photo: ''
    event_date: ''
    venue: ''
    short_description: ''
email: your-email@domain.com
description: "\n"
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
